### PR TITLE
Clean lint error for this project.

### PR DESCRIPTION
**Pull request by haoyunfeix**
CTS-1438

### CODE REVIEW

**Comment by Honry** [comment]
Please fix the conflict first.

**Comment by Honry** [comment]
@haoyunfeix, please update the commit msg.

**Comment by haoyunfeix** [comment]
Sorry? your means?

**Comment by Honry** [comment]
"Add lint tool..." in commit message is inappropriate.

**Comment by Honry** [comment]
And please also reference task CTS-1438 in your commit msg.

**Comment by Honry** [comment]
LGTM

**Pull request merged**
