### PR TITLE
[demo-express] Add config for ManifestDemo to support pack with longer version length

### PR DESCRIPTION
**Pull request by zhuyongyong**
- Add apk-version-opt attribute in suite.json for ManifestDemo3 and ManifestDemo4
- Use demo-ex-em.png of demo-express as the icon of demoexpress embiddingapi

BUG=https://crosswalk-project.org/jira/browse/XWALK-4296

### CODE REVIEW

**Comment by jennycao** [comment]
@cicili @ibelem Pls help to review

**Comment by ibelem** [comment]
@zhuyongyong Does ManifestDemo1 and ManifestDemo2 need this field?

**Comment by zhuyongyong** [comment]
@ibelem Not need for  ManifestDemo1 and ManifestDemo2, it depends on the version length on res/manifest.json. When the version length is longer than 3, it need to add apk-version-opt attribute in suite.json

**Comment by ibelem** [comment]
Thank you! LGTM

**Comment by cicili** [comment]
LGTM @jennycao

**Pull request merged**
