### PR TITLE
Remove test specific for Tizen support

### PR DESCRIPTION
**Pull request by haoxli**
https://crosswalk-project.org/jira/browse/XWALK-5273

### CODE REVIEW

**Comment by jennycao** [comment]
@haoxli Pls add your UT result info.
1. Build Test for apk
2. UT Test for webspeech
3. UT Test for typical samples

**Comment by zqzhang** [comment]
Per https://crosswalk-project.org/jira/browse/XWALK-2027, Web NFC hasn't been ready.

**Comment by haoxli** [comment]
1. Success to build apk
2. Web Speech: PASS
3. Typical Samples: PASS

**Comment by jennycao** [comment]
LGTM

**Pull request merged**
